### ISSUE TITLE
After update to 2024.11 no sensor

### ISSUE THREAD

**Issue by DieMetRik** [adamoutler/pikvm-homeassistant-integration#9]
After update to HomeAssistant 2024.11 all sensor are not avaliable 
**First ERROR**

```Log details (ERROR)
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:365
integration: Sensor ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 15:21:40 (2 occurrences)
Last logged: 15:21:58

Error while setting up pikvm_ha platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 365, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/pikvm_ha/sensor.py", line 67, in async_setup_entry
    from .sensors.pikvm_cpu_temp_sensor import PiKVMCpuTempSensor
  File "/config/custom_components/pikvm_ha/sensors/pikvm_cpu_temp_sensor.py", line 2, in <module>
    from homeassistant.core import METRIC_SYSTEM
ImportError: cannot import name 'METRIC_SYSTEM' from 'homeassistant.core' (/usr/src/homeassistant/homeassistant/core.py)
```
**Second warning**

```Logger: homeassistant.util.loop
Source: util/loop.py:136
First occurred: 15:21:34 (2 occurrences)
Last logged: 15:21:37

Detected blocking call to open with args ('/usr/local/lib/python3.12/site-packages/pytz/zoneinfo/Africa/Abidjan', 'rb') inside the event loop by custom integration 'lkcomu_interrao' at custom_components/lkcomu_interrao/_util.py, line 61: return __import__("inter_rao_energosbyt.api." + type_, globals(), locals(), ("API",)).API (offender: /usr/local/lib/python3.12/site-packages/pytz/__init__.py, line 108: return open(filename, 'rb')), please create a bug report at https://github.com/alryaz/hass-lkcomu-interrao/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 461, in _async_setup_component await asyncio.gather( File "/usr/src/homeassistant/homeassistant/setup.py", line 463, in <genexpr> create_eager_task( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 783, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 546, in async_setup await self.__async_setup_with_context(hass, integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context result = await component.async_setup_entry(hass, self) File "/config/custom_components/lkcomu_interrao/__init__.py", line 246, in async_setup_entry api_cls = import_api_cls(type_) File "/config/custom_components/lkcomu_interrao/_util.py", line 61, in import_api_cls return __import__("inter_rao_energosbyt.api." + type_, globals(), locals(), ("API",)).API
Detected blocking call to load_verify_locations with args (<ssl.SSLContext object at 0x7f8ab18c2050>, '/tmp/tmpm6uzesii.pem') inside the event loop by custom integration 'pikvm_ha' at custom_components/pikvm_ha/cert_handler.py, line 49: context.load_verify_locations(cert_file_path) (offender: /config/custom_components/pikvm_ha/cert_handler.py, line 49: context.load_verify_locations(cert_file_path)), please create a bug report at https://github.com/adamoutler/pikvm-homeassistant-integration/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_verify_locations Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 461, in _async_setup_component await asyncio.gather( File "/usr/src/homeassistant/homeassistant/setup.py", line 463, in <genexpr> create_eager_task( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 783, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 546, in async_setup await self.__async_setup_with_context(hass, integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context result = await component.async_setup_entry(hass, self) File "/config/custom_components/pikvm_ha/__init__.py", line 58, in async_setup_entry coordinator = PiKVMDataUpdateCoordinator( File "/config/custom_components/pikvm_ha/coordinator.py", line 46, in __init__ self._create_session() File "/config/custom_components/pikvm_ha/coordinator.py", line 51, in _create_session self.session, self.cert_file_path = create_session_with_cert(self.cert) File "/config/custom_components/pikvm_ha/cert_handler.py", line 49, in create_session_with_cert context.load_verify_locations(cert_file_path)```

**Comment by adamoutler** [comment]
Yes. I need to backport the changes.  Will handle this weekend.
